#!/usr/bin/env python
import string
import optparse
import os.path
import ConfigParser as configparser

SERVERS_PATH='servers'

def init(name):
    cp = configparser.ConfigParser()
    # read config file
    cp.readfp(open(os.path.join(SERVERS_PATH, name+'.conf')))
    # check if dir exists
    if os.path.isdir(os.path.join(SERVERS_PATH, name)):
        # @todo: confirm dir reset
        assert(False)
        pass
    # create standard folders
    # get components
    # create symlinks
    # generate nginx config sections
    # prompt to reload supervisord?
    pass

def update(name):
    # read config file
    # get non-existing components
    # create symlinks
    # generate nginx config sections
    # ask to update existing components
    # prompt to reload supervisord?
    pass

def run_from_args():
    usage = "usage: %prog [init|update] [name]"
    parser = optparse.OptionParser(usage=usage)
    (options, args) = parser.parse_args()
    if len(args) < 2:
        parser.print_usage()
    elif args[0] == 'init':
        init(args[1])
    elif args[0] == 'update':
        update(args[1])
    else:
        parser.print_usage()

if __name__ == '__main__':
    run_from_args()